site_name: CC-Chat
theme:
  palette:
    scheme: slate
    primary: indigo
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
  name: material
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/Concept-Collective/cc-chat
repo_name: Concept-Collective/cc-chat
edit_uri: edit/docs/docs/
